apply plugin: 'groovy'

repositories {
	mavenCentral()
}

wrapper {
	gradleVersion = '8.6'
}

dependencies {
	final GROOVY_VERSION = '4.0.19'
	final SQLITE_VERSION = '3.45.1.0'

	implementation "org.apache.groovy:groovy:${GROOVY_VERSION}"
	implementation 'ch.qos.logback:logback-classic:1.5.3'
	implementation "org.xerial:sqlite-jdbc:$SQLITE_VERSION"
	implementation 'commons-io:commons-io:2.15.1'

}

// Java options
sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

tasks.register('runScript', JavaExec) {
	description 'Run Groovy script'

	// Set main property to name of Groovy script class.
	mainClass = 'notes'

	// Set classpath for running the Groovy script.
	classpath = sourceSets.main.runtimeClasspath
}
